I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 138, in script
    e "..." with auto
  File "game/script.rpy", line 138, in <module>
    e "..." with auto
NameError: name 'auto' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 138, in script
    e "..." with auto
  File "D:\Project\Renpy\renpy-8.0.3-sdk\renpy\ast.py", line 920, in execute
    say_menu_with(self.with_, renpy.game.interface.set_transition)
  File "D:\Project\Renpy\renpy-8.0.3-sdk\renpy\ast.py", line 739, in say_menu_with
    what = renpy.python.py_eval(expression)
  File "D:\Project\Renpy\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\Project\Renpy\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 138, in <module>
    e "..." with auto
NameError: name 'auto' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 8.0.3.22090809
My Question 1.0
Tue Dec 20 17:48:59 2022
